# Generated by Django 5.2.11 on 2026-02-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schoolclass_name_alter_uroks_name_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Назва класу'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('ПН', 'Пн'), ('ВТ', 'Вт'), ('СР', 'Ср'), ('ЧТ', 'Чт'), ('ПТ', 'Пт')], max_length=2),
        ),
        migrations.AlterField(
            model_name='uroks',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва предмета'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('urok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.uroks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
